--PROJECT 3 SOLUTIONS
--Q1
SELECT EMPID
FROM HR.Employees
ORDER BY EMPID;

SELECT COUNT(*) TOTTALEMPLOYEES
FROM HR.Employees;

--Q2
SELECT REGION, COUNT(*) TOTTALEMPLOYEES
FROM HR.Employees
GROUP BY REGION;

--Q3
SELECT ORDERID, SUM(FREIGHT) TOTALAMOUNT
FROM SALES.ORDERS
GROUP BY ORDERID
ORDER BY SUM(FREIGHT);

--Q4
SELECT ORDERID, CONVERT(DATE, ORDERDATE) ORDERDATE,
CONCAT(SHIPCITY,' ',SHIPREGION) LOCATION
FROM SALES.ORDERS;

--Q5
SELECT CONCAT(FIRSTNAME,'',LASTNAME) EMPLOYEESNAMES, CITY,
LEFT (CITY, 3) ABBREVATEDCITY
FROM HR.Employees;

--Q6
SELECT LEN ('LASTNAME') AS NAMELENGHT, LASTNAME, FIRSTNAME
FROM HR.EMPLOYEES;

--Q7
SELECT SUPPLIERID, CONTACTNAME, REGION
COALESCE (REGION, 'CA')
FROM PRODUCTION.SUPPLIERS;

SELECT STUFF (REGION,'CA'), SUPPLIERID, CONTACTNAME, REGION
FROM PRODUCTION.SUPPLIERS;

--Q8
SELECT LASTNAME, FIRSTNAME,DATEDIFF(YEAR,CURRENT_TIMESTAMP, HIREDATE) YEAROFEPLOYMENT
FROM HR.Employees;

--Q9
SELECT FIRSTNAME, LASTNAME, TITLE,
YEAR(getdate()) -YEAR(BIRTHDATE)AGE
FROM HR.EMPLOYEES;

--Q10
SELECT LASTNAME,FIRSTNAME, TITLE,
YEAR(GETDATE()) - YEAR(BIRTHDATE)AGE
FROM HR.Employees
WHERE YEAR(GETDATE()) - YEAR(BIRTHDATE)>=
(SELECT AVG(YEAR(GETDATE()) - YEAR(BIRTHDATE))
FROM HR.Employees);

WITH EMAGE AS (
SELECT LASTNAME,FIRSTNAME, TITLE,
YEAR(GETDATE()) - YEAR(BIRTHDATE)AGE
FROM HR.Employees 
GROUP BY LASTNAME,FIRSTNAME, TITLE, BIRTHDATE
HAVING YEAR(GETDATE()) - YEAR(BIRTHDATE)  >= AVG(YEAR(GETDATE()) - YEAR(BIRTHDATE))
)
SELECT LASTNAME,FIRSTNAME, TITLE, AGE
FROM EMAGE





--Q11
SELECT D.N DAYS, S.N SHIFT
FROM DBO.Nums D
CROSS JOIN DBO.NUMS S
WHERE D.N <=7 AND S.N<=3
ORDER BY DAYS, SHIFT DESC;